LIBNAME FRAUDE "/dados/PLD/Modelagem_Nas/Risco_de_Credito/Fraude";
LIBNAME SURVIV "/dados/PLD/Modelagem_Nas/Risco_de_Credito/Fraude/survival";
OPTIONS COMPRESS=YES;

PROC CONTENTS DATA=SURVIV.TABELA_PETRO NOPRINT OUT=C(KEEP=NAME);RUN;

DATA SURVIV.TABELA_PETRO;
SET SURVIV.TABELA_PETRO(encoding=any);
RUN;


PROC FREQ DATA=SURVIV.TABELA_PETRO ORDER=FREQ;
TABLE 	 PETRO_LATTES PETRO_PETRO CENPES_LATTES;
RUN;



PROC SQL NOPRINT;
CREATE TABLE TEMP AS 
SELECT VINCULO,COUNT(*) AS TOTAL 
FROM SURVIV.TABELA_PETRO
GROUP BY VINCULO
ORDER BY TOTAL DESC;
RUN;



DATA TABELA_PETRO(COMPRESS=YES KEEP=ArquivoXML ANO LOCAL_FORMACN UF_PROFN UF_NASCN GRANDE_AREAN  
                                    VINCULON LN_IDADE CONTINENTEN DEDICACAON DIRECAON SEXON LN_COAUTOR
PETRO_LATTES
PETRO_PETRO
PROD_TEC);
SET SURVIV.TABELA_PETRO;
     IF LOCAL_FORMAC IN ('USP')      THEN LOCAL_FORMACN=1;
ELSE IF LOCAL_FORMAC IN ('UNESP')    THEN LOCAL_FORMACN=2;
ELSE IF LOCAL_FORMAC IN ('UFRJ')     THEN LOCAL_FORMACN=3;
ELSE IF LOCAL_FORMAC IN ('UNICAMP')  THEN LOCAL_FORMACN=4;
ELSE IF LOCAL_FORMAC IN ('UFRGS')    THEN LOCAL_FORMACN=5;
ELSE IF LOCAL_FORMAC IN ('UFMG')     THEN LOCAL_FORMACN=6;
ELSE IF LOCAL_FORMAC IN ('UFSC')     THEN LOCAL_FORMACN=7;
ELSE IF LOCAL_FORMAC IN ('UFPE')     THEN LOCAL_FORMACN=8;
ELSE IF LOCAL_FORMAC IN ('UFPA')     THEN LOCAL_FORMACN=9;
ELSE IF LOCAL_FORMAC IN ('UFPR')     THEN LOCAL_FORMACN=10;
ELSE IF LOCAL_FORMAC IN ('UFSCAR')   THEN LOCAL_FORMACN=11;
ELSE IF LOCAL_FORMAC IN ('UNB')      THEN LOCAL_FORMACN=12;
ELSE IF LOCAL_FORMAC IN ('PUC-RJ')   THEN LOCAL_FORMACN=13;
ELSE                                      LOCAL_FORMACN=14;

     IF UF_END_PROFISSIONAL IN ('SP') THEN UF_PROFN=1;
ELSE IF UF_END_PROFISSIONAL IN ('RJ') THEN UF_PROFN=2;
ELSE IF UF_END_PROFISSIONAL IN ('MG') THEN UF_PROFN=3;
ELSE IF UF_END_PROFISSIONAL IN ('RS') THEN UF_PROFN=4;
ELSE IF UF_END_PROFISSIONAL IN ('PR') THEN UF_PROFN=5;
ELSE IF UF_END_PROFISSIONAL IN ('SC') THEN UF_PROFN=6;
ELSE IF UF_END_PROFISSIONAL IN ('BA') THEN UF_PROFN=7;
ELSE IF UF_END_PROFISSIONAL IN ('PE') THEN UF_PROFN=8;
ELSE                                       UF_PROFN=9;

     IF UF_NASCIMENTO IN ('SP') THEN UF_NASCN=1;
ELSE IF UF_NASCIMENTO IN ('RJ') THEN UF_NASCN=2;
ELSE IF UF_NASCIMENTO IN ('MG') THEN UF_NASCN=3;
ELSE IF UF_NASCIMENTO IN ('RS') THEN UF_NASCN=4;
ELSE IF UF_NASCIMENTO IN ('PR') THEN UF_NASCN=5;
ELSE IF UF_NASCIMENTO IN ('SC') THEN UF_NASCN=6;
ELSE IF UF_NASCIMENTO IN ('BA') THEN UF_NASCN=7;
ELSE IF UF_NASCIMENTO IN ('PE') THEN UF_NASCN=8;
ELSE                                 UF_NASCN=9;

     IF GRANDE_AREA ='CIENCIAS_EXATAS_E_DA_TERRA' THEN GRANDE_AREAN=1;
ELSE IF GRANDE_AREA ='CIENCIAS_BIOLOGICAS'        THEN GRANDE_AREAN=2;
ELSE GRANDE_AREAN=3;

     IF VINCULO ='LIVRE'             THEN VINCULON=1;
ELSE IF VINCULO ='CELETISTA'         THEN VINCULON=2;
ELSE IF VINCULO ='SERVIDOR_PUBLICO'  THEN VINCULON=3;
ELSE VINCULON=4;

IF CONTINENTE='Brasil' THEN CONTINENTEN=1;ELSE CONTINENTEN=0;
IF DEDICACAO_EXCLUSIVA='SIM' THEN DEDICACAON =1;ELSE DEDICACAON=0;
IF DIRECAO='Brasil' THEN DIRECAON=1;ELSE DIRECAON=0;
IF SEXO ='M' THEN SEXON=1;ELSE SEXON=0;

LN_IDADE   = LOG(IDADE_ACADEMICA);
LN_COAUTOR = LOG(SUM(TOT_COAUTOR,1));
RUN;

ODS GRAPHICS ON;
ODS OUTPUT VARIMPORTANCE=IMPORTANCE;
PROC HPSPLIT DATA=TABELA_PETRO SEED=666 INTERVALBINS=99 MAXDEPTH=20
             MINVARIANCE=0.001 PLOTS=ZOOMEDTREE NODES=DETAIL ;
PARTITION FRACTION(VALIDATE=0.40 SEED=666);
TARGET PETRO_LATTES / LEVEL=NOMINAL;
/*INPUT LN_IDADE LN_COAUTOR  / LEVEL=INT;*/
INPUT  LOCAL_FORMACN UF_PROFN UF_NASCN GRANDE_AREAN VINCULON CONTINENTEN DEDICACAON DIRECAON SEXON / LEVEL=NOMINAL;
GROW CHAID /*GINI*/ ;
PRUNE  /*COSTCOMPLEXITY(LEAVES=9)*/ C45(CONFIDENCE=0.05);
OUTPUT OUT=SAIDA;
RUN;


ODS GRAPHICS ON;
/*ODS OUTPUT VARIMPORTANCE=IMPORTANCE FITSTATISTICS=fitstats(rename=(Ntrees=Trees));*/
PROC HPFOREST DATA=TABELA_PETRO maxtrees=200;
PARTITION FRACTION(VALIDATE=0.40 SEED=666);
INPUT LN_IDADE LN_COAUTOR  / LEVEL=INTERVAL;
INPUT  LOCAL_FORMACN UF_PROFN UF_NASCN GRANDE_AREAN VINCULON CONTINENTEN DEDICACAON DIRECAON SEXON / LEVEL=NOMINAL;
TARGET PETRO_LATTES / LEVEL=NOMINAL;
run;






/*INTERVALBINS=99 MAXDEPTH=12 MINCATSIZE=3 MINLEAFSIZE=3 CONFIDENCE=0.55 CHAID    : 91,00% train 90,00% test*/
/*INTERVALBINS=99 MAXDEPTH=12 MINCATSIZE=3 MINLEAFSIZE=3 CONFIDENCE=0.55 CHISQUARE: 91,00% train 91,00% test*/
/*INTERVALBINS=99 MAXDEPTH=12 MINCATSIZE=3 MINLEAFSIZE=3 CONFIDENCE=0.55 ENTROPY  : 91,63% train 91,17% test*/
/*INTERVALBINS=99 MAXDEPTH=12 MINCATSIZE=3 MINLEAFSIZE=3 CONFIDENCE=0.55 FASTCHAID: 93,90% train 91,81% test*/
/*INTERVALBINS=99 MAXDEPTH=12 MINCATSIZE=3 MINLEAFSIZE=3 CONFIDENCE=0.55 GINI     : 91,57% train 91,55% test*/

%MACRO TUNNING; 
%DO CAT=1 %TO 5;
%DO LEAF=1 %TO 5;
%DO DEPTH=5 %TO 10;
%DO CONFIDENCE=5 %TO 10;
ODS OUTPUT VarImportance=IMPORTANCE ConfusionMatrix=Confusao TreePerformance=Fit;
PROC HPSPLIT DATA=TRANSACAO_HISTORICO_VS2 SEED=666 INTERVALBINS=99 MAXDEPTH=&DEPTH.
             MINCATSIZE=&CAT. MINLEAFSIZE=&LEAF. PLOTS=ZOOMEDTREE NODES=DETAIL;
WHERE FRAUDE_BOLETO=1 OR (FRAUDE_BOLETO=0 AND FATOR_ALEATORIO<='09');
PARTITION FRACTION(VALIDATE=0.40 SEED=666);
TARGET FRAUDE_BOLETO / LEVEL=NOMINAL;
INPUT LN_VALOR LN_VALOR2 IDADE SALDO_POS CENTS / LEVEL=INT;
INPUT REDONDO TIPO FIRST_DIG SECOND_DIG HORA WEEK / LEVEL=NOMINAL;
GROW GINI;
PRUNE C45(CONFIDENCE=0.75);
OUTPUT OUT=SAIDA;
RUN;
%END;
%END;
%END;
%MEND TUNNING;
%TUNNING;

PROC MEANS DATA=SAIDA P1 P25 MEAN P95 P99 MAXDEC=4;
CLASS _Node_;
VAR P_FRAUDE_BOLETO1 V_FRAUDE_BOLETO1;
RUN;
