/*LIBNAME SURVIV "C:\Users\b2073208\Documents\Bases_Lattes";*/
LIBNAME SURVIV "C:\Users\patri\OneDrive\Área de Trabalho\corr potec";
OPTIONS COMPRESS=YES;


PROC CONTENTS DATA=SURVIV.DADOS_ESTATICOSX NOPRINT OUT=C(KEEP=NAME);
RUN;


/*---------------------------------------------------------------------*/
/*--                   TRATAMENTO DOS DADOS                          --*/
/*---------------------------------------------------------------------*/

PROC SORT DATA=SURVIV.DADOS_ESTATICOS SORTSIZE=MAX;BY ArquivoXML;RUN;
PROC SORT DATA=SURVIV.TAB_FILTRO      SORTSIZE=MAX;BY ArquivoXML;RUN;
DATA SURVIV.DADOS_ESTATICOSX(COMPRESS=YES 
                             DROP=UF_NASCIMENTO PAIS_NASCIMENTO LOCAL_FORMAC GRANDE_AREA SEXO VINCULO
                             ENCODING=ANY);
MERGE SURVIV.TAB_FILTRO(IN=A)
      SURVIV.DADOS_ESTATICOS(IN=B WHERE=(GRANDE_AREA IN ('CIENCIAS_EXATAS_E_DA_TERRA','ENGENHARIAS','OUTROS')));
IF A AND B;
BY ArquivoXML;
IF PAIS_NASCIMENTO='Brasil';
     IF UF_NASCIMENTO IN ('SP','RJ','MG','ES')      THEN UF_NASCN=1;
ELSE IF UF_NASCIMENTO IN ('RS','PR','SC')           THEN UF_NASCN=2;
ELSE IF UF_NASCIMENTO IN ('DF','MS','GO','MT')      THEN UF_NASCN=3;
ELSE IF UF_NASCIMENTO IN ('AM','PA','RR','AC','RO') THEN UF_NASCN=4;
ELSE                                                     UF_NASCN=5;

     IF LOCAL_FORMAC IN ('USP')      THEN LOCAL_FORMACN=0;
ELSE IF LOCAL_FORMAC IN ('UNICAMP')  THEN LOCAL_FORMACN=1;
ELSE IF LOCAL_FORMAC IN ('UFRJ')     THEN LOCAL_FORMACN=2;
ELSE IF LOCAL_FORMAC IN ('UFMG')     THEN LOCAL_FORMACN=3;
ELSE IF LOCAL_FORMAC IN ('UFRGS')    THEN LOCAL_FORMACN=4;
ELSE IF LOCAL_FORMAC IN ('UFPA')     THEN LOCAL_FORMACN=5;
ELSE IF LOCAL_FORMAC IN ('PUC-RJ')   THEN LOCAL_FORMACN=6;
ELSE IF LOCAL_FORMAC IN ('UFSC')     THEN LOCAL_FORMACN=7;
ELSE IF LOCAL_FORMAC IN ('UFPE')     THEN LOCAL_FORMACN=8;
ELSE IF LOCAL_FORMAC IN ('UFPR')     THEN LOCAL_FORMACN=9;
ELSE IF LOCAL_FORMAC IN ('UFF')      THEN LOCAL_FORMACN=10;
ELSE IF LOCAL_FORMAC IN ('UFBA')     THEN LOCAL_FORMACN=11;
ELSE IF LOCAL_FORMAC IN ('UNESP')    THEN LOCAL_FORMACN=12;
ELSE IF LOCAL_FORMAC IN ('UFSCAR')   THEN LOCAL_FORMACN=13;
ELSE IF LOCAL_FORMAC IN ('UFC')      THEN LOCAL_FORMACN=14;
ELSE IF LOCAL_FORMAC IN ('UFU')      THEN LOCAL_FORMACN=15;
ELSE IF LOCAL_FORMAC IN ('UFCG')     THEN LOCAL_FORMACN=16;
ELSE IF LOCAL_FORMAC IN ('UFPB')     THEN LOCAL_FORMACN=17;
ELSE IF LOCAL_FORMAC IN ('UFES')     THEN LOCAL_FORMACN=18;
ELSE                                      LOCAL_FORMACN=19;

     IF GRANDE_AREA ='CIENCIAS_EXATAS_E_DA_TERRA' THEN GRANDE_AREAN=1;
ELSE IF GRANDE_AREA ='ENGENHARIAS'                THEN GRANDE_AREAN=2;
ELSE                                                   GRANDE_AREAN=3;

IF VINCULO ='SERVIDOR_PUBLICO' THEN VINCULON=0;ELSE VINCULON=1;
IF SEXO    ='F'                THEN SEXON   =1;ELSE SEXON=0;
IF DIRECAO =1                  THEN DIRECAO =1;ELSE DIRECAO=0;


LN_IDADE       = LOG(SUM(IDADE_ACADEMICA,1));
LN_COAUTOR     = LOG(SUM(TOTAL_COAUTORES,1));
LN_LOC_TRAB    = LOG(SUM(NUM_LOCAL_TRAB,1));
LN_CAPES       = LOG(SUM(NOTA_CAPES,1));
LN_ARTG_A1_A2  = LOG(SUM(ARTG_A1_A2,1));
LN_ARTG_B1_B2  = LOG(SUM(ARTG_B1_B2,1));
LN_ARTG_B3_B4  = LOG(SUM(ARTG_B3_B4,1));
LN_ARTG_B5_C   = LOG(SUM(ARTG_B5_C ,1));
LN_ARTG_AGRARI = LOG(SUM(ARTG_AGRARI,1));
LN_ARTG_BIOLOG = LOG(SUM(ARTG_BIOLOG,1));
LN_ARTG_C_EXAT = LOG(SUM(ARTG_C_EXAT,1));
LN_ARTG_ENGENH = LOG(SUM(ARTG_ENGENH,1));
LN_ARTG_LETRAS = LOG(SUM(ARTG_LETRAS,1));
LN_ARTG_C_HUMA = LOG(SUM(ARTG_C_HUMA,1));
LN_ARTG_C_SAUD = LOG(SUM(ARTG_C_SAUD,1));
LN_ARTG_OUTROS = LOG(SUM(ARTG_OUTROS,1));
LN_ARTG_SOC_AP = LOG(SUM(ARTG_SOC_AP,1));
LN_ARTIGOS     = LOG(SUM(ARTG_A1_A2,ARTG_B1_B2,ARTG_B3_B4,ARTG_B5_C,1));

LN_ARTIGO_BRASIL     = LOG(SUM(ARTIGO_BRASIL,1));
LN_ARTIGO_EXTERIOR   = LOG(SUM(ARTIGO_EXTERIOR,1));
LN_LIVRO_BRASIL      = LOG(SUM(CAP_LIVRO_BRASIL,LIVRO_BRASIL,1));
LN_LIVRO_EXTERIOR    = LOG(SUM(CAP_LIVRO_EXTERIOR,LIVRO_EXTERIOR,1));
LN_LIVRO             = LOG(SUM(CAP_LIVRO_BRASIL,LIVRO_BRASIL,CAP_LIVRO_EXTERIOR,LIVRO_EXTERIOR,1));
LN_PATENTE_BRASIL    = LOG(SUM(PATENTE_BRASIL,1));
LN_PATENTE_EXTERIOR  = LOG(SUM(PATENTE_EXTERIOR,1));
LN_PATENTE           = LOG(SUM(PATENTE_BRASIL,PATENTE_EXTERIOR,1));

RUN;

/*----------------------------------------------------------------*/
/*--                                                            --*/
/*----------------------------------------------------------------*/

/*PROC FREQ DATA=DADOS_ESTATICOS ORDER=FREQ;TABLE PETRO /NOCOL NOPERCENT NOROW;RUN;*/
/*ANP_ANP ANP_LATTES CENPES_LATTES PETRO_LAB PETRO_LATTES PETRO_PETRO*/
PROC FREQ DATA=DADOS_ESTATICOS ORDER=FREQ NOPRINT;
where CENPES_LATTES=1 OR PETRO_PETRO=1 OR PETRO_lattes=1;
TABLE VINCULO /NOCOL NOPERCENT NOROW OUT=TEMP;
RUN;


%MACRO FREQ(TRAT,CATEG);
PROC SQL NOPRINT;
CREATE TABLE TEMP AS 
SELECT &CATEG.,&TRAT.,COUNT(*) AS TOTAL 
FROM DADOS_ESTATICOS
WHERE GRANDE_AREA IN ('CIENCIAS_EXATAS_E_DA_TERRA','ENGENHARIAS','OUTROS')
GROUP BY &CATEG.,&TRAT.
ORDER BY &CATEG.;
QUIT;

PROC TRANSPOSE DATA=TEMP OUT=TEMP(DROP=_NAME_ _LABEL_) PREFIX=TRAT_;
BY &CATEG.;
ID &TRAT.;
VAR TOTAL;
RUN;
%MEND FREQ;
%FREQ(ANP_ANP,LOCAL_FORMAC);


/*---------------------------------------------------------------------*/
/*--                    MODELAGEM DOS DADOS                          --*/
/*---------------------------------------------------------------------*/

%MACRO LOGIT(DEP);
ODS SELECT PARAMETERESTIMATES;
ODS OUTPUT PARAMETERESTIMATES=PARAM_&DEP.(DROP=DF StdErr WaldChiSq _ESTTYPE_);
PROC LOGISTIC DATA=SURVIV.DADOS_ESTATICOSX;
CLASS UF_NASCN GRANDE_AREAN SEXON VINCULON LOCAL_FORMACN;
MODEL &DEP.(REF=FIRST)=LN_IDADE LN_COAUTOR LN_LOC_TRAB LN_CAPES LOCAL_FORMACN
                       UF_NASCN GRANDE_AREAN DIRECAO SEXON VINCULON / MAXITER=80 LINK=logit LACKFIT RSQUARE;
OUTPUT OUT=SAIDA_&DEP.(KEEP=ArquivoXML ANP_ANP ANP_LATTES CENPES_LATTES PETRO_LAB PETRO_LATTES PETRO_PETRO P) PROB=P;
RUN;

%MEND LOGIT;
%LOGIT(ANP_ANP);
%LOGIT(ANP_LATTES);
%LOGIT(CENPES_LATTES);
%LOGIT(PETRO_LAB);
%LOGIT(PETRO_LATTES);
%LOGIT(PETRO_PETRO);



%MACRO KS(DEP);
PROC NPAR1WAY DATA=SAIDA_&DEP. EDF NOPRINT;
CLASS &DEP.;
VAR P;
OUTPUT OUT=KS_&DEP.(KEEP=_VAR_ _D_ RENAME=(_D_=KS));
RUN;
%MEND KS;
%KS(ANP_ANP);
%KS(ANP_LATTES);
%KS(CENPES_LATTES);
%KS(PETRO_LAB);
%KS(PETRO_LATTES);
%KS(PETRO_PETRO);


/*---------------------------------------------------------------------*/
/*--                   REGIÃO DE SUPORTE COMUM                       --*/
/*---------------------------------------------------------------------*/

%MACRO PREP(DEP);
PROC MEANS DATA=SAIDA_&DEP. NOPRINT NWAY;
CLASS &DEP.;
OUTPUT OUT=SUP_&DEP.(DROP=_FREQ_ _type_) P25(P)=PROBINF P75(P)=PROBSUP;
RUN;

PROC SQL;
CREATE TABLE SAIDA_&DEP. AS 
SELECT A.*,B.PROBSUP AS PROBSUP0,C.PROBINF AS PROBINF1
FROM SAIDA_&DEP. AS A 
CROSS JOIN SUP_&DEP. AS B 
CROSS JOIN SUP_&DEP. AS C 
WHERE B.&DEP.=0 AND C.&DEP.=1;
QUIT;

PROC SQL;
CREATE TABLE SAIDAX_&DEP. AS 
SELECT DISTINCT A.ArquivoXML,A.&DEP.,
       CASE WHEN A.&DEP.=1 THEN 1/P ELSE 1/(1-P) END AS PESO,
	   CASE WHEN A.&DEP.=1 THEN 1   ELSE P/(1-P) END AS PESOX,
       B.LN_IDADE,B.LN_COAUTOR,B.LN_LOC_TRAB,B.LN_CAPES,B.DIRECAO,
	   B.UF_NASCN,B.GRANDE_AREAN,B.SEXON,B.VINCULON,B.LOCAL_FORMACN,
	   B.LN_ARTG_A1_A2       ,
       B.LN_ARTG_B1_B2       ,
       B.LN_ARTG_B3_B4       ,
       B.LN_ARTG_B5_C        ,
       B.LN_ARTG_AGRARI      ,
       B.LN_ARTG_BIOLOG      ,
       B.LN_ARTG_C_EXAT      ,
       B.LN_ARTG_ENGENH      ,
	   B.LN_ARTG_LETRAS      ,
	   B.LN_ARTG_C_HUMA      ,
	   B.LN_ARTG_C_SAUD      ,
	   B.LN_ARTG_OUTROS      ,
	   B.LN_ARTG_SOC_AP      ,
       B.LN_ARTIGOS          ,
	   B.LN_ARTIGO_BRASIL    ,
       B.LN_ARTIGO_EXTERIOR  ,
       B.LN_LIVRO_BRASIL     ,
       B.LN_LIVRO_EXTERIOR   ,
       B.LN_LIVRO            ,
       B.LN_PATENTE_BRASIL   ,
       B.LN_PATENTE_EXTERIOR ,
       B.LN_PATENTE          

FROM SAIDA_&DEP. AS A
LEFT JOIN SURVIV.DADOS_ESTATICOSX AS B ON A.ArquivoXML=B.ArquivoXML
WHERE P<=PROBSUP0 AND P>=PROBINF1;
QUIT;

%MEND PREP;
%PREP(ANP_ANP);
%PREP(ANP_LATTES);
%PREP(CENPES_LATTES);
%PREP(PETRO_LAB);
%PREP(PETRO_LATTES);
%PREP(PETRO_PETRO);



/*---------------------------------------------------------------------*/
/*--               ABORDAGEM POR AMOSTRAGEM (ABANDONADA)             --*/
/*---------------------------------------------------------------------*/

/*
PROC SORT DATA=DADOS_ESTATICOS SORTSIZE=max;BY PETRO;RUN;
PROC SURVEYSELECT DATA=DADOS_ESTATICOS REP=500 out=AMO SAMPSIZE=(500 500) 
SEED=666 METHOD=SRS NOPRINT;
STRATA PETRO;
RUN;

PROC SORT DATA=AMO SORTSIZE=MAX;BY REPLICATE;RUN;
PROC LOGISTIC DATA=AMO NOPRINT;
BY REPLICATE ;
CLASS UF_NASCN GRANDE_AREAN SEXON VINCULON LOCAL_FORMACN;
MODEL PETRO(REF=FIRST)= LN_IDADE LN_COAUTOR LN_LOC_TRAB LN_CAPES LOCAL_FORMACN
                        UF_NASCN GRANDE_AREAN DIRECAO SEXON VINCULON / LINK=LOGIT;
OUTPUT OUT=SAIDA(KEEP=ArquivoXML REPLICATE ANP: CENPES_LATTES PETRO: P) PROB=P;
RUN;

PROC MEANS DATA=SAIDA NOPRINT NWAY;
CLASS ArquivoXML ANP_ANP ANP_LATTES CENPES_LATTES PETRO_LAB PETRO_LATTES PETRO_PETRO;
OUTPUT OUT=SAIDA2(DROP=_FREQ_ _type_) mean(P)=P;
RUN;
*/
/*---------------------------------------------------------------------*/
/*--                  CONFERÊNCIA DO TAMANHO DOS DADOS               --*/
/*---------------------------------------------------------------------*/

PROC SQL NOPRINT;
CREATE TABLE TEMP AS 
SELECT 'ANP_ANP'       AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_ANP_ANP        UNION
SELECT 'ANP_LATTES'    AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_ANP_LATTES     UNION
SELECT 'PETRO_LAB'     AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_PETRO_LAB      UNION 
SELECT 'CENPES_LATTES' AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_CENPES_LATTES  UNION
SELECT 'PETRO_PETRO'   AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_PETRO_PETRO    UNION
SELECT 'PETRO_LATTES'  AS ORG,COUNT(*) AS TOTAL FROM SAIDAX_PETRO_LATTES
ORDER BY ORG;
QUIT;


PROC DATASETS LIBRARY=WORK NOPRINT;
DELETE SUP_:(GENNUM=ALL);
DELETE PARAM_:(GENNUM=ALL);
DELETE KS_:(GENNUM=ALL);
RUN;

DATA TESTET(DROP=ANP_ANP ANP_LATTES CENPES_LATTES PETRO_LAB PETRO_LATTES PETRO_PETRO);
RETAIN ArquivoXML;
LENGTH FONTE $10.;
SET SAIDAX_ANP_ANP(IN=A) SAIDAX_ANP_LATTES(IN=B) SAIDAX_CENPES_LATTES(IN=C)
    SAIDAX_PETRO_LAB(IN=D) SAIDAX_PETRO_LATTES(IN=E) SAIDAX_PETRO_PETRO(IN=F);
KEEP ArquivoXML PESO LN_IDADE LN_COAUTOR LN_LOC_TRAB LN_CAPES FONTE PESOX
     VINCULON LOCAL_FORMACN UF_NASCN GRANDE_AREAN DIRECAO SEXON TRAT
     ANP_ANP ANP_LATTES CENPES_LATTES PETRO_LAB PETRO_LATTES PETRO_PETRO;
     IF A THEN FONTE="ANP_ANP";
ELSE IF B THEN FONTE="ANP_LATTES";
ELSE IF C THEN FONTE="CENPES_LATTES";
ELSE IF D THEN FONTE="PETRO_LAB";
ELSE IF E THEN FONTE="PETRO_LATTES";
ELSE IF F THEN FONTE="PETRO_PETRO";

     IF A THEN TRAT=ANP_ANP;
ELSE IF B THEN TRAT=ANP_LATTES;
ELSE IF C THEN TRAT=CENPES_LATTES;
ELSE IF D THEN TRAT=PETRO_LAB;
ELSE IF E THEN TRAT=PETRO_LATTES;
ELSE IF F THEN TRAT=PETRO_PETRO;

RUN;


/*EQUALITY=EQUALITY*/
PROC SORT DATA=TESTET;BY FONTE;RUN;
ODS SELECT TTESTS;
ODS OUTPUT TTESTS=TTESTS(DROP=DF Method WHERE=(Variances="Unequal"));
PROC TTEST DATA=TESTET;
BY FONTE;
CLASS TRAT;
VAR LN_IDADE LN_COAUTOR LN_LOC_TRAB LN_CAPES VINCULON 
    LOCAL_FORMACN UF_NASCN GRANDE_AREAN DIRECAO SEXON ;
WEIGHT PESOX;
RUN;


DATA TTESTS(DROP=Probt tValue2 Variances);
SET TTESTS;
tValue2=ROUND(tValue,0.01);
     IF Probt<=0.001 THEN tValue3=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"***");
ELSE IF Probt<=0.025 THEN tValue3=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"**");
ELSE IF Probt<=0.050 THEN tValue3=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"*");
ELSE                      tValue3=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"ns");
RUN;


PROC SORT DATA=TTESTS;BY Variable;RUN;
PROC TRANSPOSE DATA=TTESTS OUT=tValue_(DROP=_NAME_ _LABEL_) PREFIX=tValue_;
BY Variable;
VAR tValue3;
ID FONTE;
RUN;




/*---------------------------------------------------------------------*/
/*--             ATE: REGRESSÃO COM PESO PARA OBTER ATE              --*/
/*---------------------------------------------------------------------*/

%MACRO ATE(VAR,TRAT);
ODS SELECT PARAMETERESTIMATES;
ODS OUTPUT PARAMETERESTIMATES=BET_&VAR.(KEEP=Dependent Estimate Probt tValue Variable WHERE=(Variable="&TRAT."));
PROC REG DATA=SAIDAX_&TRAT.;
MODEL &VAR. = &TRAT.;
WEIGHT PESO;
RUN;QUIT;

DATA BET_&VAR.(DROP=Probt tValue tValue2);SET BET_&VAR.(RENAME=(Estimate=&TRAT.));
tValue2=ROUND(tValue,0.01);
     IF Probt<=0.001 THEN t_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"***");
ELSE IF Probt<=0.025 THEN t_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"**");
ELSE IF Probt<=.050  THEN t_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"*");
ELSE                      t_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"ns");
RUN;
%MEND ATE;
%ATE(LN_ARTG_A1_A2       ,ANP_ANP);
%ATE(LN_ARTG_B1_B2       ,ANP_ANP);
%ATE(LN_ARTG_B3_B4       ,ANP_ANP);
%ATE(LN_ARTG_B5_C        ,ANP_ANP);
%ATE(LN_ARTG_AGRARI      ,ANP_ANP);
%ATE(LN_ARTG_BIOLOG      ,ANP_ANP);
%ATE(LN_ARTG_C_EXAT      ,ANP_ANP);
%ATE(LN_ARTG_ENGENH      ,ANP_ANP);
%ATE(LN_ARTG_LETRAS      ,ANP_ANP);
%ATE(LN_ARTG_C_HUMA      ,ANP_ANP);
%ATE(LN_ARTG_C_SAUD      ,ANP_ANP);
%ATE(LN_ARTG_OUTROS      ,ANP_ANP);
%ATE(LN_ARTG_SOC_AP      ,ANP_ANP);
%ATE(LN_ARTIGOS          ,ANP_ANP);
%ATE(LN_ARTIGO_BRASIL    ,ANP_ANP);
%ATE(LN_ARTIGO_EXTERIOR  ,ANP_ANP);
%ATE(LN_LIVRO_BRASIL     ,ANP_ANP);
%ATE(LN_LIVRO_EXTERIOR   ,ANP_ANP);
%ATE(LN_LIVRO            ,ANP_ANP);
%ATE(LN_PATENTE_BRASIL   ,ANP_ANP);
%ATE(LN_PATENTE_EXTERIOR ,ANP_ANP);
%ATE(LN_PATENTE          ,ANP_ANP);

DATA ATE_ANP_ANP(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATE(LN_ARTG_A1_A2       ,ANP_LATTES); 
%ATE(LN_ARTG_B1_B2       ,ANP_LATTES); 
%ATE(LN_ARTG_B3_B4       ,ANP_LATTES);  
%ATE(LN_ARTG_B5_C        ,ANP_LATTES); 
%ATE(LN_ARTG_AGRARI      ,ANP_LATTES);
%ATE(LN_ARTG_BIOLOG      ,ANP_LATTES);
%ATE(LN_ARTG_C_EXAT      ,ANP_LATTES);
%ATE(LN_ARTG_ENGENH      ,ANP_LATTES);
%ATE(LN_ARTG_LETRAS      ,ANP_LATTES);
%ATE(LN_ARTG_C_HUMA      ,ANP_LATTES);
%ATE(LN_ARTG_C_SAUD      ,ANP_LATTES);
%ATE(LN_ARTG_OUTROS      ,ANP_LATTES);
%ATE(LN_ARTG_SOC_AP      ,ANP_LATTES);
%ATE(LN_ARTIGOS          ,ANP_LATTES);
%ATE(LN_ARTIGO_BRASIL    ,ANP_LATTES);
%ATE(LN_ARTIGO_EXTERIOR  ,ANP_LATTES);
%ATE(LN_LIVRO_BRASIL     ,ANP_LATTES);
%ATE(LN_LIVRO_EXTERIOR   ,ANP_LATTES);
%ATE(LN_LIVRO            ,ANP_LATTES);
%ATE(LN_PATENTE_BRASIL   ,ANP_LATTES);
%ATE(LN_PATENTE_EXTERIOR ,ANP_LATTES);
%ATE(LN_PATENTE          ,ANP_LATTES);
DATA ATE_ANP_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);
RUN;

%ATE(LN_ARTG_A1_A2       ,PETRO_LAB); 
%ATE(LN_ARTG_B1_B2       ,PETRO_LAB); 
%ATE(LN_ARTG_B3_B4       ,PETRO_LAB);  
%ATE(LN_ARTG_B5_C        ,PETRO_LAB); 
%ATE(LN_ARTG_AGRARI      ,PETRO_LAB);
%ATE(LN_ARTG_BIOLOG      ,PETRO_LAB);
%ATE(LN_ARTG_C_EXAT      ,PETRO_LAB);
%ATE(LN_ARTG_ENGENH      ,PETRO_LAB);
%ATE(LN_ARTG_LETRAS      ,PETRO_LAB);
%ATE(LN_ARTG_C_HUMA      ,PETRO_LAB);
%ATE(LN_ARTG_C_SAUD      ,PETRO_LAB);
%ATE(LN_ARTG_OUTROS      ,PETRO_LAB);
%ATE(LN_ARTG_SOC_AP      ,PETRO_LAB);
%ATE(LN_ARTIGOS          ,PETRO_LAB);
%ATE(LN_ARTIGO_BRASIL    ,PETRO_LAB);
%ATE(LN_ARTIGO_EXTERIOR  ,PETRO_LAB);
%ATE(LN_LIVRO_BRASIL     ,PETRO_LAB);
%ATE(LN_LIVRO_EXTERIOR   ,PETRO_LAB);
%ATE(LN_LIVRO            ,PETRO_LAB);
%ATE(LN_PATENTE_BRASIL   ,PETRO_LAB);
%ATE(LN_PATENTE_EXTERIOR ,PETRO_LAB);
%ATE(LN_PATENTE          ,PETRO_LAB);
DATA ATE_PETRO_LAB(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);
RUN;

%ATE(LN_ARTG_A1_A2       ,CENPES_LATTES); 
%ATE(LN_ARTG_B1_B2       ,CENPES_LATTES); 
%ATE(LN_ARTG_B3_B4       ,CENPES_LATTES);  
%ATE(LN_ARTG_B5_C        ,CENPES_LATTES); 
%ATE(LN_ARTG_AGRARI      ,CENPES_LATTES);
%ATE(LN_ARTG_BIOLOG      ,CENPES_LATTES);
%ATE(LN_ARTG_C_EXAT      ,CENPES_LATTES);
%ATE(LN_ARTG_ENGENH      ,CENPES_LATTES);
%ATE(LN_ARTG_LETRAS      ,CENPES_LATTES);
%ATE(LN_ARTG_C_HUMA      ,CENPES_LATTES);
%ATE(LN_ARTG_C_SAUD      ,CENPES_LATTES);
%ATE(LN_ARTG_OUTROS      ,CENPES_LATTES);
%ATE(LN_ARTG_SOC_AP      ,CENPES_LATTES);
%ATE(LN_ARTIGOS          ,CENPES_LATTES);
%ATE(LN_ARTIGO_BRASIL    ,CENPES_LATTES);
%ATE(LN_ARTIGO_EXTERIOR  ,CENPES_LATTES);
%ATE(LN_LIVRO_BRASIL     ,CENPES_LATTES);
%ATE(LN_LIVRO_EXTERIOR   ,CENPES_LATTES);
%ATE(LN_LIVRO            ,CENPES_LATTES);
%ATE(LN_PATENTE_BRASIL   ,CENPES_LATTES);
%ATE(LN_PATENTE_EXTERIOR ,CENPES_LATTES);
%ATE(LN_PATENTE          ,CENPES_LATTES);
DATA ATE_CENPES_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);
RUN;

%ATE(LN_ARTG_A1_A2       ,PETRO_PETRO); 
%ATE(LN_ARTG_B1_B2       ,PETRO_PETRO); 
%ATE(LN_ARTG_B3_B4       ,PETRO_PETRO);  
%ATE(LN_ARTG_B5_C        ,PETRO_PETRO); 
%ATE(LN_ARTG_AGRARI      ,PETRO_PETRO);
%ATE(LN_ARTG_BIOLOG      ,PETRO_PETRO);
%ATE(LN_ARTG_C_EXAT      ,PETRO_PETRO);
%ATE(LN_ARTG_ENGENH      ,PETRO_PETRO);
%ATE(LN_ARTG_LETRAS      ,PETRO_PETRO);
%ATE(LN_ARTG_C_HUMA      ,PETRO_PETRO);
%ATE(LN_ARTG_C_SAUD      ,PETRO_PETRO);
%ATE(LN_ARTG_OUTROS      ,PETRO_PETRO);
%ATE(LN_ARTG_SOC_AP      ,PETRO_PETRO);
%ATE(LN_ARTIGOS          ,PETRO_PETRO);
%ATE(LN_ARTIGO_BRASIL    ,PETRO_PETRO);
%ATE(LN_ARTIGO_EXTERIOR  ,PETRO_PETRO);
%ATE(LN_LIVRO_BRASIL     ,PETRO_PETRO);
%ATE(LN_LIVRO_EXTERIOR   ,PETRO_PETRO);
%ATE(LN_LIVRO            ,PETRO_PETRO);
%ATE(LN_PATENTE_BRASIL   ,PETRO_PETRO);
%ATE(LN_PATENTE_EXTERIOR ,PETRO_PETRO);
%ATE(LN_PATENTE          ,PETRO_PETRO);
DATA ATE_PETRO_PETRO(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);
RUN;

%ATE(LN_ARTG_A1_A2       ,PETRO_LATTES); 
%ATE(LN_ARTG_B1_B2       ,PETRO_LATTES); 
%ATE(LN_ARTG_B3_B4       ,PETRO_LATTES);  
%ATE(LN_ARTG_B5_C        ,PETRO_LATTES); 
%ATE(LN_ARTG_AGRARI      ,PETRO_LATTES);
%ATE(LN_ARTG_BIOLOG      ,PETRO_LATTES);
%ATE(LN_ARTG_C_EXAT      ,PETRO_LATTES);
%ATE(LN_ARTG_ENGENH      ,PETRO_LATTES);
%ATE(LN_ARTG_LETRAS      ,PETRO_LATTES);
%ATE(LN_ARTG_C_HUMA      ,PETRO_LATTES);
%ATE(LN_ARTG_C_SAUD      ,PETRO_LATTES);
%ATE(LN_ARTG_OUTROS      ,PETRO_LATTES);
%ATE(LN_ARTG_SOC_AP      ,PETRO_LATTES);
%ATE(LN_ARTIGOS          ,PETRO_LATTES);
%ATE(LN_ARTIGO_BRASIL    ,PETRO_LATTES);
%ATE(LN_ARTIGO_EXTERIOR  ,PETRO_LATTES);
%ATE(LN_LIVRO_BRASIL     ,PETRO_LATTES);
%ATE(LN_LIVRO_EXTERIOR   ,PETRO_LATTES);
%ATE(LN_LIVRO            ,PETRO_LATTES);
%ATE(LN_PATENTE_BRASIL   ,PETRO_LATTES);
%ATE(LN_PATENTE_EXTERIOR ,PETRO_LATTES);
%ATE(LN_PATENTE          ,PETRO_LATTES);
DATA ATE_PETRO_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);
RUN;


PROC SORT DATA=ATE_ANP_ANP      ;BY Dependent;RUN;
PROC SORT DATA=ATE_ANP_LATTES   ;BY Dependent;RUN;
PROC SORT DATA=ATE_PETRO_LAB    ;BY Dependent;RUN;
PROC SORT DATA=ATE_CENPES_LATTES;BY Dependent;RUN;
PROC SORT DATA=ATE_PETRO_PETRO  ;BY Dependent;RUN;
PROC SORT DATA=ATE_PETRO_LATTES ;BY Dependent;RUN;

DATA ATE;
RETAIN Dependent ANP_ANP T_ANP_ANP ANP_LATTES T_ANP_LATTES CENPES_LATTES T_CENPES_LATTES 
       PETRO_LAB T_PETRO_LAB PETRO_LATTES T_PETRO_LATTES PETRO_PETRO T_PETRO_PETRO;
MERGE ATE_ANP_ANP ATE_ANP_LATTES ATE_PETRO_LAB ATE_CENPES_LATTES ATE_PETRO_PETRO ATE_PETRO_LATTES;
BY Dependent;
RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE ATE_:(GENNUM=ALL);
RUN;


/*---------------------------------------------------------------------*/
/*--             ATT: REGRESSÃO COM PESO PARA OBTER ATT              --*/
/*---------------------------------------------------------------------*/
%MACRO ATT(VAR,TRAT);
ODS SELECT PARAMETERESTIMATES;
ODS OUTPUT PARAMETERESTIMATES=BET_&VAR.(KEEP=Dependent Estimate Probt tValue Variable WHERE=(Variable="&TRAT."));
PROC REG DATA=SAIDAX_&TRAT.;
MODEL &VAR. = &TRAT.;
WEIGHT PESOX;
RUN;

DATA BET_&VAR.(DROP=Probt tValue tValue2);SET BET_&VAR.(RENAME=(Estimate=&TRAT.));
tValue2=ROUND(tValue,0.01);
     IF Probt<=0.001 THEN T_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"***");
ELSE IF Probt<=0.025 THEN T_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"**");
ELSE IF Probt<=.050  THEN T_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"*");
ELSE                      T_&TRAT.=COMPRESS(INPUT(COMPRESS(tValue2),$5.)||"ns");
RUN;
%MEND ATT;
%ATT(LN_ARTG_A1_A2       ,ANP_ANP); 
%ATT(LN_ARTG_B1_B2       ,ANP_ANP); 
%ATT(LN_ARTG_B3_B4       ,ANP_ANP);  
%ATT(LN_ARTG_B5_C        ,ANP_ANP); 
%ATT(LN_ARTG_AGRARI      ,ANP_ANP);
%ATT(LN_ARTG_BIOLOG      ,ANP_ANP);
%ATT(LN_ARTG_C_EXAT      ,ANP_ANP);
%ATT(LN_ARTG_ENGENH      ,ANP_ANP);
%ATT(LN_ARTG_LETRAS      ,ANP_ANP);
%ATT(LN_ARTG_C_HUMA      ,ANP_ANP);
%ATT(LN_ARTG_C_SAUD      ,ANP_ANP);
%ATT(LN_ARTG_OUTROS      ,ANP_ANP);
%ATT(LN_ARTG_SOC_AP      ,ANP_ANP);
%ATT(LN_ARTIGOS          ,ANP_ANP);
%ATT(LN_ARTIGOS          ,ANP_ANP);
%ATT(LN_ARTIGO_BRASIL    ,ANP_ANP);
%ATT(LN_ARTIGO_EXTERIOR  ,ANP_ANP);
%ATT(LN_LIVRO_BRASIL     ,ANP_ANP);
%ATT(LN_LIVRO_EXTERIOR   ,ANP_ANP);
%ATT(LN_LIVRO            ,ANP_ANP);
%ATT(LN_PATENTE_BRASIL   ,ANP_ANP);
%ATT(LN_PATENTE_EXTERIOR ,ANP_ANP);
%ATT(LN_PATENTE          ,ANP_ANP);

DATA ATT_ANP_ANP(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATT(LN_ARTG_A1_A2       ,ANP_LATTES); 
%ATT(LN_ARTG_B1_B2       ,ANP_LATTES); 
%ATT(LN_ARTG_B3_B4       ,ANP_LATTES);  
%ATT(LN_ARTG_B5_C        ,ANP_LATTES); 
%ATT(LN_ARTG_AGRARI      ,ANP_LATTES);
%ATT(LN_ARTG_BIOLOG      ,ANP_LATTES);
%ATT(LN_ARTG_C_EXAT      ,ANP_LATTES);
%ATT(LN_ARTG_ENGENH      ,ANP_LATTES);
%ATT(LN_ARTG_LETRAS      ,ANP_LATTES);
%ATT(LN_ARTG_C_HUMA      ,ANP_LATTES);
%ATT(LN_ARTG_C_SAUD      ,ANP_LATTES);
%ATT(LN_ARTG_OUTROS      ,ANP_LATTES);
%ATT(LN_ARTG_SOC_AP      ,ANP_LATTES);
%ATT(LN_ARTIGOS          ,ANP_LATTES);
%ATT(LN_ARTIGO_BRASIL    ,ANP_LATTES);
%ATT(LN_ARTIGO_EXTERIOR  ,ANP_LATTES);
%ATT(LN_LIVRO_BRASIL     ,ANP_LATTES);
%ATT(LN_LIVRO_EXTERIOR   ,ANP_LATTES);
%ATT(LN_LIVRO            ,ANP_LATTES);
%ATT(LN_PATENTE_BRASIL   ,ANP_LATTES);
%ATT(LN_PATENTE_EXTERIOR ,ANP_LATTES);
%ATT(LN_PATENTE          ,ANP_LATTES);

DATA ATT_ANP_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATT(LN_ARTG_A1_A2       ,PETRO_LAB); 
%ATT(LN_ARTG_B1_B2       ,PETRO_LAB); 
%ATT(LN_ARTG_B3_B4       ,PETRO_LAB);  
%ATT(LN_ARTG_B5_C        ,PETRO_LAB); 
%ATT(LN_ARTG_AGRARI      ,PETRO_LAB);
%ATT(LN_ARTG_BIOLOG      ,PETRO_LAB);
%ATT(LN_ARTG_C_EXAT      ,PETRO_LAB);
%ATT(LN_ARTG_ENGENH      ,PETRO_LAB);
%ATT(LN_ARTG_LETRAS      ,PETRO_LAB);
%ATT(LN_ARTG_C_HUMA      ,PETRO_LAB);
%ATT(LN_ARTG_C_SAUD      ,PETRO_LAB);
%ATT(LN_ARTG_OUTROS      ,PETRO_LAB);
%ATT(LN_ARTG_SOC_AP      ,PETRO_LAB);
%ATT(LN_ARTIGOS          ,PETRO_LAB);
%ATT(LN_ARTIGO_BRASIL    ,PETRO_LAB);
%ATT(LN_ARTIGO_EXTERIOR  ,PETRO_LAB);
%ATT(LN_LIVRO_BRASIL     ,PETRO_LAB);
%ATT(LN_LIVRO_EXTERIOR   ,PETRO_LAB);
%ATT(LN_LIVRO            ,PETRO_LAB);
%ATT(LN_PATENTE_BRASIL   ,PETRO_LAB);
%ATT(LN_PATENTE_EXTERIOR ,PETRO_LAB);
%ATT(LN_PATENTE          ,PETRO_LAB);

DATA ATT_PETRO_LAB(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATT(LN_ARTG_A1_A2       ,CENPES_LATTES); 
%ATT(LN_ARTG_B1_B2       ,CENPES_LATTES); 
%ATT(LN_ARTG_B3_B4       ,CENPES_LATTES);  
%ATT(LN_ARTG_B5_C        ,CENPES_LATTES); 
%ATT(LN_ARTG_AGRARI      ,CENPES_LATTES);
%ATT(LN_ARTG_BIOLOG      ,CENPES_LATTES);
%ATT(LN_ARTG_C_EXAT      ,CENPES_LATTES);
%ATT(LN_ARTG_ENGENH      ,CENPES_LATTES);
%ATT(LN_ARTG_LETRAS      ,CENPES_LATTES);
%ATT(LN_ARTG_C_HUMA      ,CENPES_LATTES);
%ATT(LN_ARTG_C_SAUD      ,CENPES_LATTES);
%ATT(LN_ARTG_OUTROS      ,CENPES_LATTES);
%ATT(LN_ARTG_SOC_AP      ,CENPES_LATTES);
%ATT(LN_ARTIGOS          ,CENPES_LATTES);
%ATT(LN_ARTIGOS          ,CENPES_LATTES);
%ATT(LN_ARTIGO_BRASIL    ,CENPES_LATTES);
%ATT(LN_ARTIGO_EXTERIOR  ,CENPES_LATTES);
%ATT(LN_LIVRO_BRASIL     ,CENPES_LATTES);
%ATT(LN_LIVRO_EXTERIOR   ,CENPES_LATTES);
%ATT(LN_LIVRO            ,CENPES_LATTES);
%ATT(LN_PATENTE_BRASIL   ,CENPES_LATTES);
%ATT(LN_PATENTE_EXTERIOR ,CENPES_LATTES);
%ATT(LN_PATENTE          ,CENPES_LATTES);

DATA ATT_CENPES_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATT(LN_ARTG_A1_A2       ,PETRO_PETRO);
%ATT(LN_ARTG_B1_B2       ,PETRO_PETRO);
%ATT(LN_ARTG_B3_B4       ,PETRO_PETRO);
%ATT(LN_ARTG_B5_C        ,PETRO_PETRO);
%ATT(LN_ARTG_AGRARI      ,PETRO_PETRO);
%ATT(LN_ARTG_BIOLOG      ,PETRO_PETRO);
%ATT(LN_ARTG_C_EXAT      ,PETRO_PETRO);
%ATT(LN_ARTG_ENGENH      ,PETRO_PETRO);
%ATT(LN_ARTG_LETRAS      ,PETRO_PETRO);
%ATT(LN_ARTG_C_HUMA      ,PETRO_PETRO);
%ATT(LN_ARTG_C_SAUD      ,PETRO_PETRO);
%ATT(LN_ARTG_OUTROS      ,PETRO_PETRO);
%ATT(LN_ARTG_SOC_AP      ,PETRO_PETRO);
%ATT(LN_ARTIGOS          ,PETRO_PETRO);
%ATT(LN_ARTIGO_BRASIL    ,PETRO_PETRO);
%ATT(LN_ARTIGO_EXTERIOR  ,PETRO_PETRO);
%ATT(LN_LIVRO_BRASIL     ,PETRO_PETRO);
%ATT(LN_LIVRO_EXTERIOR   ,PETRO_PETRO);
%ATT(LN_LIVRO            ,PETRO_PETRO);
%ATT(LN_PATENTE_BRASIL   ,PETRO_PETRO);
%ATT(LN_PATENTE_EXTERIOR ,PETRO_PETRO);
%ATT(LN_PATENTE          ,PETRO_PETRO);


DATA ATT_PETRO_PETRO(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

%ATT(LN_ARTG_A1_A2       ,PETRO_LATTES);
%ATT(LN_ARTG_B1_B2       ,PETRO_LATTES);
%ATT(LN_ARTG_B3_B4       ,PETRO_LATTES);
%ATT(LN_ARTG_B5_C        ,PETRO_LATTES);
%ATT(LN_ARTG_AGRARI      ,PETRO_LATTES);
%ATT(LN_ARTG_BIOLOG      ,PETRO_LATTES);
%ATT(LN_ARTG_C_EXAT      ,PETRO_LATTES);
%ATT(LN_ARTG_ENGENH      ,PETRO_LATTES);
%ATT(LN_ARTG_LETRAS      ,PETRO_LATTES);
%ATT(LN_ARTG_C_HUMA      ,PETRO_LATTES);
%ATT(LN_ARTG_C_SAUD      ,PETRO_LATTES);
%ATT(LN_ARTG_OUTROS      ,PETRO_LATTES);
%ATT(LN_ARTG_SOC_AP      ,PETRO_LATTES);
%ATT(LN_ARTIGOS          ,PETRO_LATTES);
%ATT(LN_ARTIGOS          ,PETRO_LATTES);
%ATT(LN_ARTIGO_BRASIL    ,PETRO_LATTES);
%ATT(LN_ARTIGO_EXTERIOR  ,PETRO_LATTES);
%ATT(LN_LIVRO_BRASIL     ,PETRO_LATTES);
%ATT(LN_LIVRO_EXTERIOR   ,PETRO_LATTES);
%ATT(LN_LIVRO            ,PETRO_LATTES);
%ATT(LN_PATENTE_BRASIL   ,PETRO_LATTES);
%ATT(LN_PATENTE_EXTERIOR ,PETRO_LATTES);
%ATT(LN_PATENTE          ,PETRO_LATTES);


DATA ATT_PETRO_LATTES(DROP=Variable);SET BET_LN:;RUN;

PROC DATASETS LIBRARY=WORK NOPRINT;DELETE BET_LN_:(GENNUM=ALL);RUN;

PROC SORT DATA=ATT_ANP_ANP      ;BY Dependent;RUN;
PROC SORT DATA=ATT_ANP_LATTES   ;BY Dependent;RUN;
PROC SORT DATA=ATT_PETRO_LAB    ;BY Dependent;RUN;
PROC SORT DATA=ATT_CENPES_LATTES;BY Dependent;RUN;
PROC SORT DATA=ATT_PETRO_PETRO  ;BY Dependent;RUN;
PROC SORT DATA=ATT_PETRO_LATTES ;BY Dependent;RUN;

DATA ATT(COMPRESS=YES);
RETAIN Dependent ANP_ANP T_ANP_ANP ANP_LATTES T_ANP_LATTES CENPES_LATTES T_CENPES_LATTES 
       PETRO_LAB T_PETRO_LAB PETRO_LATTES T_PETRO_LATTES PETRO_PETRO T_PETRO_PETRO;
MERGE ATT_ANP_ANP ATT_ANP_LATTES ATT_PETRO_LAB ATT_CENPES_LATTES ATT_PETRO_PETRO ATT_PETRO_LATTES;
BY Dependent;
RUN;


PROC DATASETS LIBRARY=WORK NOPRINT;DELETE ATT_:(GENNUM=ALL);
RUN;